- hosts: localhost
  connection: local

  vars_files:
    - ansible_vars.yml

  tasks:
    - name: Get VSwitch ID
      ali_vswitch_facts:
        alicloud_region: "{{ global.alicloud_region }}"
        name_prefix: "{{ vpc.vsw_name }}"
        filters:
          zone_id: "{{ global.alicloud_zone }}"
      register: vsw_facts

    - name: Get Group ID
      ali_security_group_facts:
        alicloud_region: "{{ global.alicloud_region }}"
        name_prefix: "{{ vpc.sg_name }}"
        filters:
          zone_id: "{{ global.alicloud_zone }}"
      register: sg_facts

    - name: Create a set of instances
      ali_instance:
        instance_name: "{{ instance.instance_name }}"
        alicloud_region: "{{ global.alicloud_region }}"
        alicloud_zone: "{{ global.alicloud_zone }}"
        instance_type: "{{ instance.instance_type }}"
        image_id: "{{ instance.ami_id }}"
        host_name: "{{ instance.instance_name }}"
        key_name: "{{ instance.key_name }}"
        system_disk_category: "{{ instance.system_disk_category }}"
        allocate_public_ip: true
        internet_charge_type: PayByTraffic
        max_bandwidth_out: 5
        vswitch_id: "{{ vsw_facts.vswitches[0].id }}"
        security_groups: "{{ sg_facts.groups[0].id }}"
        tags:
          Name: AnsiblePerfTest
        count: 1
        count_tag:
          Name: AnsiblePerfTest
      register: create_instance
